public with sharing class DataManyPagesController{
    /*
    private Integer pageNumber = 0;
    public Integer getPageNumber(){
        return pageNumber;
    }
    
    private Integer totalPages = 0;
    public Intger getTotalPages(){
        return totalPages;
    }
    
    private String contextItem = '';
    public void setContextItem(String itemStr){
        this.contextItem = itemStr;
    }
    public String getContextItem(){
        return contextItem;
    }
    
    private ApexPages.StandardSetController setCon;
    
    public DataManyPagesController{
        
        // Gather data and show in many pages
        this.setCon = new ApexPages.StandardSetController([Select Id, FirstName, LastName, Title, Phone, Email From Contact]);
        this.setCon.setPageNumber(1);
        this.setCon.setPageSize(10);
    }
    
    public void doPreviousAction(){
    
    }
    
    public void doNextAction(){
    
    }
    
    //public with sharing class 
    */
}